// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return firebaseConfig;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANSi5VvvwDrPdoqTWFxkN0yaA-wdH9LJQ',
    appId: '1:429295762575:android:703be69a0c44c850dcc4fa',
    messagingSenderId: '429295762575',
    projectId: 'isdex-68054',
    databaseURL: 'https://isdex-68054-default-rtdb.firebaseio.com',
    storageBucket: 'isdex-68054.firebasestorage.app',
  );

  static const FirebaseOptions firebaseConfig = FirebaseOptions(
  apiKey: "AIzaSyAjchC2JIXTF8rAU47dLV_chJjegTpGddM",
  authDomain: "isdex-68054.firebaseapp.com",
  databaseURL: "https://isdex-68054-default-rtdb.firebaseio.com",
  projectId: "isdex-68054",
  storageBucket: "isdex-68054.firebasestorage.app",
  messagingSenderId: "429295762575",
  appId: "1:429295762575:web:fac4496971e8e864dcc4fa"
  );

}